### ISSUE TITLE
App的下载和介绍页

### ISSUE THREAD

**Issue by ivanzhang2** [haxibiao/buyueta#10]
类似https://dongmeiwei.com/apps
因为 buyueta.com 有自己的网站首页，所以下载app页不是首页，单独放 /apps 目录下

**Comment by zixin** [comment]
下个星期我们开始做个页面吧，你有什么需要的图片给我弄得，发邮件给我！

**Comment by gaoxuan-haxibiao** [comment]
下周我整理下
