### ISSUE TITLE
消息页

### ISSUE THREAD

**Issue by zixin** [haxibiao/buyueta#15]

**Comment by gaoxuan-haxibiao** [comment]
已完成

**Comment by ivanzhang2** [comment]
1. 所有评论里， 中间那条@别用灰色...
2. @我的里面，每条的context menu 需要点开能 回复，忽略，屏蔽...
3. 1:1聊天页面还没有...

**Comment by zixin** [comment]
评论的灰色已经去除，也可以点开回复，删除，但是没有回复的按钮了！

**Comment by gaoxuan-haxibiao** [comment]
回复按钮只有评论页有。。。     你说的应该是@页
