### ISSUE TITLE
发现页  ui

### ISSUE THREAD

**Issue by zixin** [haxibiao/buyueta#17]
需要有
1. 顶部 搜索框
2 置顶的帖子的图片的滚动swiper
3. 能按 推荐，附近，话题 排序
4. item的图片能按九宫格的形式展示，1张照片时，需要能完全展示该照片最大尺寸而不是在九宫格中.

![buyueta_find](https://user-images.githubusercontent.com/13308603/37940936-eeaa7376-319d-11e8-9e16-09041bc78e46.gif)

**Comment by ivanzhang2** [comment]
排序卡附近，推荐，话题需要修改成滑动卡片(tab navigation)..
