### ISSUE TITLE
迁移去年做的buyuta.com网站前端代码

### ISSUE THREAD

**Issue by ivanzhang2** [haxibiao/buyueta#9]
到新的 laravel 5.6 上，用 vue 2.5 , boostrap 4.0
确保
原来的页面还能正常
首页不要还是爱你城的过期页面了，原来不约TA有个首页的。

**Comment by gaoxuan-haxibiao** [comment]
byt.com 前端代码迁移完成  代码已提交

**Comment by ivanzhang2** [comment]
彭聪:

为这个新项目准备运维脚本：
run push
run seed
run update

还有run ui
还有 getsql.sh
...
